#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.mathjax',
    'sphinx.ext.githubpages']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst']

# Benutzung von :numref: Referenzen zu Abbildungen
numfig = True


# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'NFCAA'
copyright = '2017, Dieter Konrad'
author = 'Dieter Konrad'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# version = '1.0'
# The full version, including alpha/beta/rc tags.
release = '1.4'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'de'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Options for LaTeX output ---------------------------------------------
f = open('preamble.tex', 'r+');
PREAMBLE = f.read();

latex_elements = {

    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    'pointsize': '11pt',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',

    # 'releasename': " ",
    # 'release':" ",
    # 'babel': '',
    # 'printindex': '',
    # 'fontenc': '',
    # 'inputenc': '',
    # 'classoptions': '',
    # 'utf8extra': '',

    # Make this not look like a book
    'classoptions': ',oneside',
     # Additional stuff for the LaTeX preamble.
    'preamble': PREAMBLE
}

latex_show_pagerefs = False
latex_domain_indices = False
# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]). article
latex_documents = [
    (master_doc, 'Projektarbeit.tex', u'Einsatz von NFC-Technologien zur Realisierung der Authentifizierung und Autorisierung mobiler Endgerate im Forschungsprojekt [meinLaden]',
     'Dieter Konrad', 'manual'),
]
