@startuml
hide footbox
title Kommunikation zwischen Alice und Bob\n
skinparam monochrome true
skinparam shadowing false
skinparam componentStyle uml2


Alice -> Bob: Authentication Request

alt successful case

    Bob -> Alice: Authentication Accepted

else some kind of failure

    Bob -> Alice: authenticationFailure()

    Alice -> Alice: ichHänge()
    group My own label
    	Alice -> Log : startLogAttack()

        loop 1000 times
            Alice -> Bob: DNS Attack
            |||
        end

    	Alice -> Log : Log attack end
    end

else Another type of failure

   Bob -> Alice: Please repeat

end

@enduml
